### ISSUE TITLE
Conceptual problem

### ISSUE THREAD

**Issue by johannesgerer** [maurizzzio/interval-arithmetic#4]
It is unclear what type of intervals the `Interval` class represents.

The difference of two closed (or open) intervals gives a half-open interval. Which cannot be represented by the Interval class.

The difference of two half-open intervals is again a half open interval. But if the Intervall class is to represent half-open intervals, this breaks the `sub` method, as the this gives a open (or closed) intervall.

Further:
in the current implementation: Interval.intersection(Interval(0,3),Interval(3,4)) == Interval(3)

which is only true for closed intervals.

The list goes on.
...

Did I missunderstand something?

**Comment by maurizzzio** [comment]
This library always uses closed intervals, if you want to represent open intervals use `nextafter`

```js
import nextAfter from 'nextafter'
import Interval from 'interval-arithmetic'

const prev = (v) => nextAfter(v, -Infinity)
const next = (v) => nextAfter(v, Infinity)

// [2, 3]
console.log( Interval(2, 3) )
// (2, 3]
console.log( Interval(next(2), 3) )
// [2, 3)
console.log( Interval(2, prev(3)) )
// (2, 3)
console.log( Interval(next(2), prev(3)) )
```

This library wraps the methods above like this

```js
function prev (v) {
  if (v === Infinity) {
    return v
  }
  return nextafter(v, -Infinity)
}
function next (v) {
  if (v === -Infinity) {
    return v
  }
  return nextafter(v, Infinity)
}
```

**Comment by johannesgerer** [comment]
ok. maybe a pointer to the boost library would be helpful, to understand the semantics.

**Comment by maurizzzio** [comment]
The readme explains really well what an interval for this library is, also there's a link to boost's interval interval implementation

I've also added three methods to represent open and half open intervals, check out the homepage for `open`, `halfOpenRight` and `halfOpenLeft`
