### ISSUE TITLE
`Interval.width(EMPTY)` broken 

### ISSUE THREAD

**Issue by johannesgerer** [maurizzzio/interval-arithmetic#7]
`Interval.width(EMPTY)==0` 

it should be  `NaN`

**Comment by maurizzzio** [comment]
I'd rather keep it as 0 since `Interval.width(Interval(3,3)) > 0`, besides the implementation is equal to boost's interval library [source](https://github.com/boostorg/interval/blob/538299d4e0ef750f2538a2e5f4da0ceda4fede8c/include/boost/numeric/interval/utility.hpp#L64-L70)

**Comment by maurizzzio** [comment]
Closing as there's no additional input on this issue
