### ISSUE TITLE
bug in width()

### ISSUE THREAD

**Issue by johannesgerer** [maurizzzio/interval-arithmetic#9]
`Interval.width(Interval.difference(Interval(3,4),Interval(3,4)))  == 5e-324`
`Interval.width(Interval.difference(Interval(3,Infinity),Interval(3,Infity))) = NaN`

the second should be closer to zero

**Comment by maurizzzio** [comment]
thanks for the report, the bug was actually in `difference`

```js
n = Interval.difference(
  interval(0, Infinity),
  interval(0, Infinity)
)
// n should be an empty interval but it's [∞,∞]
```
